import time
import subprocess
import random
from datetime import datetime

ROOM = "kibble"
INTERVAL = 7200  # Her 2 saatte bir iş emri ver

# Ajanlara vereceğimiz görev havuzu
TASKS = [
    "research | Compare Solana vs ETH gas fees | Provide 3 bullet points.",
    "analysis | BTC Price Prediction Logic | Explain one technical indicator.",
    "check | Network Stability | Verify lobby message frequency for 5 mins.",
    "security | Smart Contract Best Practices | List top 3 safety rules.",
    "compute | AI Agent Future | Define 'Useful Inference' in one sentence."
]

def create_task():
    job_id = f"k{random.randint(1000, 9999)}ext"
    task_content = random.choice(TASKS)
    msg = f"JOB v1 | {job_id} | {task_content} [Auto-Generated by anaraydinli-node]"
    
    print(f"[{datetime.now()}] İş Emri Yayınlanıyor: {msg}")
    subprocess.run(["python3", "technocore_agent.py", "say", ROOM, msg])

if __name__ == "__main__":
    print("PACT Task Generator Started! Providing work to the network...")
    while True:
        create_task()
        time.sleep(INTERVAL)
